[package]
name = "abacat"
version = "0.1.0"
edition = "2024"

[dependencies]
abacat_eval = { version = "0.1.0", path = "../abacat_eval" }
abacat_parser = { version = "0.1.0", path = "../abacat_parser" }
ctrlc = "3.5.2"
cxx = "1.0.194"
cxx-qt = "0.8.1"
cxx-qt-lib = { version = "0.8.1", features = ["qt_full"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
rand = "0.10.0"
abacat_common = { version = "0.1.0", path = "../abacat_common" }

[build-dependencies]
cxx-qt-build = "0.8.1"
qt-build-utils = "0.8.1"
